version: '3.7'
services:
    app:
        build:
            context: ..
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - ..:/workspace
        entrypoint: ''
        command: sleep infinity
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper_container
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        container_name: kafka_container
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_CREATE_TOPICS: "tweets:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
