on:
    push:
        branches:
            - main
        tags-ignore:
            - '**'

name: merge-to-main

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Run checks
        uses: ./.github/actions/run-checks

      - name: Documentation Test
        run: |
          source .venv/bin/activate
          make docs-test
