on:
    pull_request:
        types: [opened, synchronize, reopened]

name: on-pull-request

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Run checks
        uses: ./.github/actions/run-checks

      - name: Documentation Test
        run: |
          source .venv/bin/activate
          make docs-test
